apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-defender-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-defender-app
  template:
    metadata:
      labels:
        app: data-defender-app
    spec:
      containers:
      - name: data-defender-app
        image: data_defender_app:latest
        ports:
        - containerPort: 3000